### ISSUE TITLE
Update getting started guide in Azure documentation

### ISSUE THREAD

**Issue by sandeepmistry** [Azure/azure-iot-arduino#10]
We'll need to update this to reflect:
- The change in library name
- Updated example paths

https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/arduinoide-arduino-wifi101-c.md

**Comment by sandeepmistry** [comment]
@stefangordon @obsoleted what are your thoughts on this page? Should we continue to maintain it, or move more documentation to this repo and link to it from the Azure documentation?

**Comment by obsoleted** [comment]
The long term decision for this will be tied to the resolution of #2 and how the final code flow works. If we can get to a point where everything is coming from the upstream SDK then all the documentation will be in one place. But since the upstream SDK repo has a fair bit of complexity with the multitude of languages/devices it supports that is likely to take some time.

Since we do want most things to be in the upstream SDK I suggest that we leave it there and make revisions as needed. Perhaps in the PR to update the upstream documentation we can open up the discussion to the maintainers there.

**Comment by sandeepmistry** [comment]
Sounds good. Once the new release is out, could you please submit a PR for the relevant upstream documentation changes.

**Comment by tameraw** [comment]
Getting started docs are available here:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-arduino-huzzah-esp8266-get-started
