### ISSUE TITLE
fork/exec {runtime.tools.python.path}/python: no such file or directory 

### ISSUE THREAD

**Issue by khushvir** [Azure/azure-iot-arduino#109]
fork/exec {runtime.tools.python.path}/python: no such file or directory
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

Arduino IDE version 1.8.11
ESP core 2.6.3

After following the steps mentioned I got above error while compiling

How to resolve this issue.

**Comment by jbobotek** [comment]
Have you tried installing python?

**Comment by khushvir** [comment]
Python is already installed.  Problem started after I have pasted "platform.local.txt"

**Comment by jbobotek** [comment]
yeah, the platform.local.txt that you pasted is for ESP core 2.5.2. To use 2.6.3, please follow the alternate instructions and add the define(s) to build.extra_flags in the platform.txt in your 2.6.3 folder (or clone it as a platform.local.txt and add it there.)

**Comment by Ellerbach** [comment]
To help some others, from the platform.local.txt, replace ```{runtime.tools.python.path}/python``` by ```{runtime.tools.python3.path}/python3``` and that will work like a charm.

**Comment by roboknight** [comment]
Ultimately, it appears that $HOME/.arduino15/packages/esp8266/tools/python/3.7.2-post1/python was a symbolic link pointing to python.  It likely is because I'm using an older arduino version and Ubuntu's Hirsute no longer has "python"... it has "python3" and, if you install it "python2".  So ultimately, I just had to fix the underlying link and the error went away.  The better solution is to update, but I didn't feel like it.  If anyone needs to do this for another reason, thought I'd put this here.  Again, it is likely better to just update.
