### ISSUE TITLE
simplesample_http fails on ESP8266

### ISSUE THREAD

**Issue by esell** [Azure/azure-iot-arduino#27]
Hello, I've setup a new IoT hub, added my device and modified the sample code as instructed but am getting the following error:

```
Fetched NTP epoch time is: 1476801841
IoT Hub SDK for C, version 1.0.1
IoTHubClient accepted the message for delivery
HTTPS connection to eshome.azure-devices.net failed
unable to recover sending to a working state
unable to HTTPAPIEX_ExecuteRequest
```

This is on an Adafruit ESP8266 Huzzah using Arduino IDE 1.6.12 and I can confirm that the ESP8266 is connected to my wifi router. Is this something others are seeing or local to me?

Thanks!

**Comment by mamokarz** [comment]
Hi esell,

It is probably because of the IDE version that you are using. Please try Arduino IDE 1.6.9, and the esp8266 by ESP8266 Community version 2.2.0.

BTW, there are a tutorial on https://azure.microsoft.com/en-us/documentation/samples/iot-hub-c-huzzah-getstartedkit/ that uses the remote_monitoring, which is more interesting than the simplesample_http.

**Comment by esell** [comment]
Just an update. I basically cleared out all of my crap and did a fresh install of the Arduino IDE 1.6.9 and the 2.2.0 version of the esp8266 stuff. I had to compile a few times (not sure why yet) but it eventually ended up building AND is working. 

I had been using the git version of the esp8266 library so I might play around and see if the latest IDE + esp8266 2.2.0 works.

**Comment by esell** [comment]
I can confirm that everything works with the latest Arduino IDE as long as you use version 2.2.0 of the esp8266 libs 😃

**Comment by mamokarz** [comment]
Great, thanks for the feedback!
