### ISSUE TITLE
Problem with sending events to the Azure IoT Hub

### ISSUE THREAD

**Issue by remcoploeg** [Azure/azure-iot-arduino#33]
Hello,

I have installed the sample code and when I run it, I see these errors in the log on the Arduino Serial Output: (running this on an ESP8266). But I don't have any clue what is wrong...

Log:

connected with EnGenius0E148E, channel 2
dhcp client start...
ip:192.168.2.21,mask:255.255.255.0,gw:192.168.2.254
retrying ... f r0, failed ... scandone
retrying ... f 0, failed ... scandone
retrying ... f -180, failed ... scandone
chg_B1:-140
chg_B1:-100
chg_B1:-60
retrying ... f r-60, failed ... scandone
retrying ... f 0, failed ... scandone
retrying ... f -180, failed ... scandone

**Comment by mamokarz** [comment]
Can you please provide more information about your test?

1. Each Arduino are you using (here are many versions of ESP8266)?
2. Each sample are you running (name of the ino file can help)?
3. Version of the libraries (mainly AzureIoTHub, and esp8266)?

**Comment by astaykov** [comment]
Hi remcoploeg, this is caused by the WiFi connection check logic in the simplesample_http.ino file.
Check the following code section:
`void initWifi() {
#ifdef ARDUINO_SAMD_FEATHER_M0
    // for the Adafruit WINC1500 we need to enable the chip
    pinMode(WINC_EN, OUTPUT);
    digitalWrite(WINC_EN, HIGH);
#endif

    // check for the presence of the shield :
    if (WiFi.status() == WL_NO_SHIELD) {
        Serial.println("WiFi shield not present");
        // don't continue:
        while (true);
    }

    // attempt to connect to Wifi network:
    Serial.print("Attempting to connect to SSID: ");
    Serial.println(ssid);

    // Connect to WPA/WPA2 network. Change this line if using open or WEP network:
    while (WiFi.begin(ssid, pass) != WL_CONNECTED) {
        delay(4000);
        if(WiFi.status() == WL_CONNECTED)
        {
          break;
        }
        // unsuccessful, retry in 4 seconds
        Serial.print("failed ... ");
        Serial.print("retrying ... ");
    }

    Serial.println("Connected to wifi");
}`
And replace it with:
`void initWifi() {
#ifdef ARDUINO_SAMD_FEATHER_M0
    // for the Adafruit WINC1500 we need to enable the chip
    pinMode(WINC_EN, OUTPUT);
    digitalWrite(WINC_EN, HIGH);
#endif

    // check for the presence of the shield :
    if (WiFi.status() == WL_NO_SHIELD) {
        Serial.println("WiFi shield not present");
        // don't continue:
        while (true);
    }

    // attempt to connect to Wifi network:
    Serial.print("Attempting to connect to SSID: ");
    Serial.println(ssid);

    // Connect to WPA/WPA2 network. Change this line if using open or WEP network:
    while (WiFi.begin(ssid, pass) != WL_CONNECTED) {
        delay(4000);
        if(WiFi.status() == WL_CONNECTED)
        {
          break;
        }
        // unsuccessful, retry in 4 seconds
        Serial.print("failed ... ");
        Serial.print("retrying ... ");
    }

    Serial.println("Connected to wifi");
}`

this will fix your issue with the WiFi initialisation.

General note to the Authors - I believe it is good to give WiFi.begin() a little time to set the things up before assuming it has failed. I know that by documentation the begin function should return WL_CONNECTED if it is connected, but for some boards it is not exactly the case. Even the official Arduino doc regarding WiFi gives the WiFi.begin a time of 10 seconds before assuming connect failure: [Arduino WiFi Connect with WPA](https://www.arduino.cc/en/Tutorial/ConnectWithWPA)

**Comment by tameraw** [comment]
@remcoploeg - Please retry with our recent changes and let us know if problem still persists.
